name: Run CF Jatim AIO

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
            apiToken: ${{ secrets.CF }}
